$ErrorActionPreference = "Stop"

$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$targetFilename = Join-Path $Root "lua/tardis/libraries/libraries/libraries/sh_version_generated.lua"

# Release tags are plain X.Y.Z. The repo also carries older release-NN-* tags, which must not match.
$tagGlob = '[0-9]*.[0-9]*.[0-9]*'

Push-Location $Root
try {
    $sha     = git rev-parse --short HEAD 2>$null
    $exact   = git describe --tags --exact-match --match $tagGlob HEAD 2>$null
    $base    = git describe --tags --abbrev=0 --match $tagGlob HEAD 2>$null
    $commits = if ($base) { [int](git rev-list "$base..HEAD" --count 2>$null) } else { 0 }
}
finally {
    Pop-Location
}

# The describe calls above are probes and are meant to fail (no exact tag, or no tags at all in a
# shallow CI checkout). A failed native command leaves $LASTEXITCODE set, which callers such as
# glua-check.ps1 read as this script having failed.
$global:LASTEXITCODE = 0

$inCI = [bool]$env:GITHUB_ACTIONS

# A local checkout is always "source" even when it happens to sit on a release tag - it is not
# the artifact that shipped. Only CI produces the real channels.
$channel = if (-not $inCI)                      { "source" }
           elseif ($exact)                      { "release" }
           elseif ($env:GITHUB_REF_NAME -eq 'alpha') { "alpha" }
           else                                 { "beta" }

$version = if ($exact) { $exact } elseif ($base) { $base } else { $null }

if (-not $version) {
    Write-Warning "No release tag reachable from HEAD; falling back to 0.0.0. (Shallow clone, or a fork without tags?)"
    $version = "0.0.0"
    $commits = 0
}

$major, $minor, $patch = $version -split '\.'

Write-Host "Version: $version ($channel, $commits commit(s) since, $sha)"

$content = [System.Text.StringBuilder]::new()

$null = $content.AppendLine("-- AUTO GENERATED FILE - DO NOT EDIT --")
$null = $content.AppendLine("-- Generated by scripts/generate-version.ps1 --")
$null = $content.AppendLine()
$null = $content.AppendLine("TARDIS.Version = {")
$null = $content.AppendLine("    Major = $major,")
$null = $content.AppendLine("    Minor = $minor,")
$null = $content.AppendLine("    Patch = $patch")
$null = $content.AppendLine("}")
$null = $content.AppendLine()
$null = $content.AppendLine("TARDIS.Build = {")
$null = $content.AppendLine("    Channel = `"$channel`",")
$null = $content.AppendLine("    Commits = $commits,")
$null = $content.AppendLine("    Sha = `"$sha`"")
$null = $content.AppendLine("}")

Write-Host "Writing version to $targetFilename"

Set-Content -NoNewline -Path $targetFilename -Value $content
