name: Generate Files

on:
  pull_request_target:
    branches:
    - dev
    paths:
    - i18n/languages/*.json
    - version.json
    - generate-languages.ps1
    - .github/workflows/generate-files.yml
  push:
    branches:
    - dev
    paths:
    - i18n/languages/*.json
    - version.json
    - generate-languages.ps1
    - .github/workflows/generate-files.yml

  workflow_dispatch:

jobs:
  generate_files:
    name: Generate Files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
        if: github.event_name == 'pull_request'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Generate Languages
        run: ./generate-languages.ps1
        shell: pwsh
        env:
          TARDIS_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate Version
        run: ./generate-version.ps1
        shell: pwsh

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: "Update Generated Files"
