name: Generate Files

on:
  pull_request_target:
    branches:
    - dev
    paths:
    - i18n/languages/*.json
    - version.json
    - generate-languages.ps1
    - .github/workflows/generate-files.yml
  push:
    branches:
    - dev
    paths:
    - i18n/languages/*.json
    - version.json
    - generate-languages.ps1
    - .github/workflows/generate-files.yml

  workflow_dispatch:

jobs:
  generate_files:
    name: Generate Files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
        if: github.event_name == 'pull_request'

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Generate Languages
        run: ./generate-languages.ps1
        shell: pwsh
        env:
          TARDIS_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate Version
        run: ./generate-version.ps1
        shell: pwsh

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7
        with:
          commit_message: "Update Generated Files"
