name: Generate Files

on:
  pull_request_target:
    branches:
    - main
    paths:
    - i18n/languages/*.json
    - scripts/generate-languages.ps1
    - .github/workflows/generate-files.yml
  push:
    branches:
    - main
    paths:
    - i18n/languages/*.json
    - scripts/generate-languages.ps1
    - .github/workflows/generate-files.yml

  workflow_dispatch:

jobs:
  generate_files:
    name: Generate Files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
        if: github.event_name == 'pull_request'

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Generate Languages
        run: ./scripts/generate-languages.ps1
        shell: pwsh
        env:
          TARDIS_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "Update Generated Files"
